#!/bin/bash
# deploy-free.sh - Automated free deployment setup
# This script prepares everything for Vercel + Render + Supabase

set -e

echo "🆓 Free Deployment Setup for Nineveh Gifted School"
echo "=================================================="
echo ""

# Check if git repo exists
if [ ! -d ".git" ]; then
    echo "📦 Initializing Git repository..."
    git init
    git add .
    git commit -m "Initial commit: Nineveh Gifted School"
    echo "✅ Git initialized"
else
    echo "✅ Git repository exists"
fi

echo ""
echo "📋 Next Steps (Manual - 15 minutes total):"
echo "=========================================="
echo ""
echo "1️⃣  SUPABASE (3 min):"
echo "   → Go to https://supabase.com"
echo "   → New Project: 'nineveh-gifted-school'"
echo "   → Copy Pooled Connection String (port 6543, ?pgbouncer=true)"
echo "   → Save as: SUPABASE_DATABASE_URL"
echo ""
echo "2️⃣  GITHUB (2 min):"
echo "   → Create repo at https://github.com/new"
echo "   → Name: nineveh-gifted-school"
echo "   → Run these commands:"
echo "      git remote add origin https://github.com/YOUR_USERNAME/nineveh-gifted-school.git"
echo "      git branch -M main"
echo "      git push -u origin main"
echo ""
echo "3️⃣  RENDER BACKEND (5 min):"
echo "   → Go to https://dashboard.render.com"
echo "   → New + → Web Service → Connect your repo"
echo "   → Root Directory: server"
echo "   → Build: npm install && npx prisma generate && npx prisma migrate deploy"
echo "   → Start: npm start"
echo "   → Add Environment Variables:"
echo "      NODE_ENV=production"
echo "      PORT=3001"
echo "      DATABASE_URL=<your-supabase-pooled-url>"
echo "      JWT_SECRET=<auto-generate>"
echo "      CLIENT_URL=https://your-app.vercel.app"
echo "   → Plan: Free"
echo ""
echo "4️⃣  VERCEL FRONTEND (3 min):"
echo "   → Go to https://vercel.com/new"
echo "   → Import your repo"
echo "   → Root Directory: client"
echo "   → Framework: Vite (auto-detected)"
echo "   → Add Environment Variable:"
echo "      VITE_API_URL=https://your-backend.onrender.com"
echo "   → Deploy"
echo ""
echo "5️⃣  CONNECT CORS (1 min):"
echo "   → Copy Vercel URL (e.g., https://nineveh-gifted.vercel.app)"
echo "   → In Render: Update CLIENT_URL to match Vercel URL"
echo "   → Save → Auto redeploys"
echo ""
echo "🔗 Useful URLs after deploy:"
echo "   Frontend: https://your-app.vercel.app"
echo "   Backend:  https://your-backend.onrender.com"
echo "   Health:   https://your-backend.onrender.com/api/health"
echo ""
echo "📖 Full guide: FREE_DEPLOYMENT.md"
echo "🗄️  Supabase guide: SUPABASE_SETUP.md"
echo ""
echo "💡 Pro tip: Add UptimeRobot (free) to ping /api/health every 5 min"
echo "   to prevent Render free tier from sleeping."
echo ""
echo "🎉 Ready to deploy! Follow the steps above."